version: "3"

services:
  proxy:
    container_name: "regulondb-regulondb_app-nginx"
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    image: regulondbapp-nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    networks:
      - regulondbapp

  web:
    container_name: "regulondb-regulondb_app-react"
    build:
      context: .
      dockerfile: Dockerfile
      target: webapp
      args:
        API_URL: /graphql
    image: regulondbapp-react
    ports:
      - "5000:5000"
    depends_on:
      - api
      - db
    networks:
      - regulondbapp

  api:
    container_name: "regulondb-regulondb_app-graphql"
    build:
      context: .
      dockerfile: Dockerfile
      target: graphql
    image: regulondbapp-graphql
    env_file:
      - ./api-variables.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - regulondbapp

  db:
    container_name: "regulondb-regulondb_app-mongodb"
    build:
      context: .
      dockerfile: Dockerfile
      target: mongo
    image: regulondbapp-mongo
    ports:
      - "27017:27017"
    networks:
      - regulondbapp

networks:
  regulondbapp:
    driver: bridge
