version: "3"

services:
  proxy:
    container_name: "regulondb-regulondb_app-nginx"
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    image: regulondbapp-nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - datamartsApi
    networks:
      - regulondbapp

  web:
    container_name: "regulondb-regulondb_app-react"
    build:
      context: .
      dockerfile: Dockerfile
      target: webapp
      args:
        API_URL: /graphql
    image: regulondbapp-react
    ports:
      - "5000:3000"
    depends_on:
      - datamartsApi
      - db
    networks:
      - regulondbapp

  htApi:
    container_name: "regulondb_app-graphql-ht"
    build:
      context: .
      dockerfile: Dockerfile
      target: graphql-ht
    image: regulondbapp-graphql-ht
    env_file:
      - ./ht-api-variables.env
    ports:
      - "4004:4004"
    depends_on:
      - db
    networks:
      - regulondbapp

  datamartsApi:
    container_name: "regulondb_app-graphql-dm"
    build:
      context: .
      dockerfile: Dockerfile
      target: graphql-dm
    image: regulondbapp-graphql
    env_file:
      - ./api-variables.env
    ports:
      - "4000:4000"
    depends_on:
      - htApi
      - db
    networks:
      - regulondbapp

  db:
    container_name: "regulondb_app-mongodb"
    build:
      context: .
      dockerfile: Dockerfile
      target: mongo
    image: regulondbapp-mongo
    ports:
      - "27017:27017"
    networks:
      - regulondbapp

networks:
  regulondbapp:
    driver: bridge
